services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1
    container_name: cloudflare-ddns
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    network_mode: host
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      PROXIED: false
      IP6_PROVIDER: none
      DOMAINS: >
        ${AIOMANAGER_HOSTNAME?},
        ${AIOMETADATA_HOSTNAME?},
        ${AIOSTREAMS_HOSTNAME?},
        ${BAZARR_HOSTNAME?},
        ${BESZEL_HOSTNAME?},
        ${BYPARR_HOSTNAME?},
        ${COMET_HOSTNAME?},
        ${DOZZLE_HOSTNAME?},
        ${FORGEJO_HOSTNAME?},
        ${GRAFANA_HOSTNAME?},
        ${HOMEPAGE_HOSTNAME?},
        ${IMMICH_HOSTNAME?},
        ${JELLYFIN_HOSTNAME?},
        ${NTFY_HOSTNAME?},
        ${OUTLINE_HOSTNAME?},
        ${POCKET_ID_HOSTNAME?},
        ${PRISMARR_HOSTNAME?},
        ${PROMETHEUS_HOSTNAME?},
        ${PROWLARR_HOSTNAME?},
        ${QBIT_HOSTNAME?},
        ${QUI_HOSTNAME?},
        ${RADARR_HOSTNAME?},
        ${SABNZBD_HOSTNAME?},
        ${SEEDSTREAM_HOSTNAME?},
        ${SEERR_HOSTNAME?},
        ${SONARR_HOSTNAME?},
        ${STREMTHRU_HOSTNAME?},
        ${TECHNITIUM_HOSTNAME?},
        ${TINYAUTH_HOSTNAME?},
        ${TRAEFIK_HOSTNAME?},
        ${TRANSMISSION_HOSTNAME?},
        ${UPTIME_KUMA_HOSTNAME?},
        ${VAULT_HOSTNAME?}
    profiles:
      - cloudflare-ddns
      - required
      - all
