services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: kuma
    restart: unless-stopped
    # environment:
      # PUID: ${PUID}
      # PGID: ${PGID}
    expose:
      - 3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`${UPTIME_KUMA_HOSTNAME?}`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt"
      - "traefik.http.routers.uptime-kuma.middlewares=tinyauth@docker"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    volumes:
      - ${DOCKER_DATA_DIR}/uptime-kuma:/app/data
    depends_on:
      socket-proxy:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.25"
    profiles:
      - uptime-kuma
      - monitoring
      - all
