services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    volumes:
      - ${DOCKER_DATA_DIR}/gluetun:/gluetun
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamnzb.rule=Host(`${STREAMNZB_HOSTNAME?}`)"
      - "traefik.http.routers.streamnzb.entrypoints=websecure"
      - "traefik.http.routers.streamnzb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.streamnzb.middlewares=tinyauth@docker"
      - "traefik.http.services.streamnzb.loadbalancer.server.port=7000"
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 1m
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.25"
    profiles:
      - aiostreams
      - all


